### ISSUE TITLE
D0S.DustManager and D0S.Factory - Dust... conflict?

### ISSUE THREAD

**Issue by NickGrease** [d0sboots/PerfectTower#11]
Ok, let me lay out what I _**think**_ is an issue: DustManager won't up tier a single dust (as in count==1) and FactoryManager _**only**_ leaves a single dust. This for me has led to more than a few instances of manual up tiering. (Poor me, I know) Plus, for an added kicker, 2nd floor crafter happily eats everything, right down to the last dust, making it rather dangerous to use with low numbers of higher tier dust (not your problem, just mentioning some pain points). 

I'm just entering mid game, so maybe this won't be an issue later on.

Not really looking for a fix, just thought I'd mention it as a possible point for a second look. 

Love your scripts/tools - thanks for everything!

EDIT: I suppose if I could ask for anything:
- Crafting ore lumps up to X tier using available previous tier dust
- A setting to strictly save a certain amount of Ore per tier (think 100 rubber saplings)

**Comment by d0sboots** [comment]
Yes, you're right about this discrepancy. It's caused some low-level annoyance for a while, and I've thought about changing it but have been too lazy to do so.

There *is* a setting to save a certain amount of ore per tier... for the uptierer, not the factory. Factory is already too complicated ^_^;

The reason for the limitation of the uptierer not using the last dust is both for safety, and also (more importantly) this keeps the inventory from being reordered. The factory doesn't do this, which means it will rearrange your items when it uses them all up.

The solution to using both together is to ensure that the up-tierer stays in front of the factory. I.e. don't make so much stuff that the factory runs through all the dust. If you stick to that, it's never an issue, because the uptierer does all the uptiering and the factory never does.

I never use the built-in crafter, but it's interesting to know that it doesn't save anything. Doesn't really surprise me, though.

**Comment by NickGrease** [comment]
Thanks again for your reply. As I expected, a few days after posting this, with the appropriate perks and finally getting access to the power plant second floor, I was processing ore at a rate fast enough that dust manager became obsolete. Thanks for the detailed explanation though!

**Comment by d0sboots** [comment]
The dust manager is still relevant at that point; you can get a lot of extra high-tier dust from all the T1 dust you pull in (but you have to be willing to idle in the factory).
When it really becomes obsolete is when you get factory floor 2.
