### ISSUE TITLE
Feature Request : Machine Sets

### ISSUE THREAD

**Issue by Thornstromb** [d0sboots/PerfectTower#7]
Requesting a crafting group to make a single full set of machines at a given tier. This would be massively helpful for the initial up-tiering process. As an aside, the readme should note that while you have to pull out a machine in order to upgrade it, it is easier and more helpful to have 2 sets of machines you alternate upgrades between, as the second set, once up-tiering is done, can be used to produce your first exotic producer.

**Comment by d0sboots** [comment]
That already exists: Category 'grup', type 'machines'.

The alternate procedure you outline is potentially easier, but it's also more expensive: You'll end up with an extra set of T9 machines at the end. Not everyone wants that, especially because not everyone dives right in to making exotics after getting T10 machines. I prefer to explain the more complicated procedure that more people want, most people can figure out the alternating tiers strat on their own.
