### ISSUE TITLE
Create Version of Factory script that works without chemical lumps

### ISSUE THREAD

**Issue by KeinNiemand** [d0sboots/PerfectTower#8]
I don't have chemical lumps (not even close) yet but I don't want to manually do ore lumps in the factory. A Version of the script that works without chemicals lumps would be usefull. I don't want to completly ignore or manually use the factory until I am able to get chemical lumps.

**Comment by d0sboots** [comment]
You can use my uptiering script to do ore lumps; it works with or without chemical lumps. It also will save you time, because by uptiering constantly, you don't have to wait for the factory to do it on-demand.

I'm not likely to add this to the factory itself, because it would add a significant amount of complication, and ideally you shouldn't be needing to uptier a lot of stuff until you have chemical lumps anyway. (It becomes a severe waste of ore.)
